title = "Файл с диалогами"

[[dialogs]]
id = 1
person_name = "UNO"
person_img_path = "./123.img"
phase = "What's you do?"

    [answe_one]
    psahe = "I ..."
    dialog_id = 2

    [answe_two]
    psahe = "I do ..."
    dialog_id = 3

    [answe_three]
    psahe = "I ..."
    dialog_id = 3

    [answe_four]
    psahe = "???"
    dialog_id = 0

[[dialogs]]
id = 2
person_name = "UNO"
person_img_path = "./123.img"
phase = "-_-"
    [answe_one]
    psahe = "-__-"
    dialog_id = 0

    [answe_two]
    psahe = "--_--"
    dialog_id = 0

    [answe_three]
    psahe = "--_-"
    dialog_id = 0

    [answe_four]
    psahe = "-_--"
    dialog_id = 0

[[dialogs]]
id = 43
person_name = "UNO"
person_img_path = "./123.img"
phase = "( ͡° ͜ʖ ͡°)"
    [answe_one]
    psahe = "(ಥ﹏ಥ)"
    dialog_id = 0

    [answe_two]
    psahe = "(ᵔᴥᵔ)"
    dialog_id = 0

    [answe_three]
    psahe = "(ง ͠° ͟ل͜ ͡°)ง"
    dialog_id = 0

    [answe_four]
    psahe = "(ง°ل͜°)ง"
    dialog_id = 0
